services:
  - type: web
    name: wedding-quiz-app
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-northeast-1
      - key: DYNAMODB_TABLE_PREFIX
        value: wedding_quiz_